#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

source ops/ci/lib.sh

cleanup() {
  rm -f agent/repo-score.json agent/repo-score.md
}
trap cleanup EXIT

rewrite_with_header() {
  local header_file="$1"
  local target_file="$2"
  local tmp
  if cmp -s "$header_file" <(head -n "$(wc -l <"$header_file")" "$target_file"); then
    return 0
  fi
  tmp="$(mktemp)"
  {
    cat "$header_file"
    tail -n +1 "$target_file"
  } >"$tmp"
  mv "$tmp" "$target_file"
}

# Refresh the committed README badge artifacts from the public score report.
jankurai audit . --mode ratchet --full --baseline agent/baselines/main.repo-score.json --json agent/repo-score.json --md agent/repo-score.md --no-score-history

json_header="$(mktemp)"
cat >"$json_header" <<'EOF'
// Generated by: jankurai audit . --mode ratchet --full --baseline agent/baselines/main.repo-score.json --json agent/repo-score.json --md agent/repo-score.md --no-score-history
// Source: agent/badge.toml
// Regenerate: `bash ops/ci/jankurai-badge.sh`
// DO NOT EDIT BY HAND.
EOF
rewrite_with_header "$json_header" agent/jankurai-badge.json
rm -f "$json_header"

# For agent/jankurai-badge.svg, inject the provenance header *inside* the
# <svg> root element (after the opening tag), not before it. GitHub's blob
# viewer (https://github.com/<owner>/<repo>/blob/main/agent/jankurai-badge.svg)
# fails with "Invalid image source" when the SVG file does not start with
# `<svg` or `<?xml`, but jankurai's generated-zone rule
# (HLT-002-GENERATED-MUTATION) only requires the header text to appear
# in the file — it does not have to be the literal first line.
inject_svg_header() {
  local svg_file="$1"
  if sed -n '2p' "$svg_file" | grep -q '^<!-- Generated by:'; then
    return 0
  fi
  local tmp
  tmp="$(mktemp)"
  {
    head -n 1 "$svg_file"
    printf '%s\n' \
      '<!-- Generated by: jankurai audit . --mode ratchet --full --baseline agent/baselines/main.repo-score.json --json agent/repo-score.json --md agent/repo-score.md --no-score-history -->' \
      '<!-- Source: agent/badge.toml -->' \
      '<!-- Regenerate: `bash ops/ci/jankurai-badge.sh` -->' \
      '<!-- DO NOT EDIT BY HAND. -->'
    tail -n +2 "$svg_file"
  } >"$tmp"
  mv "$tmp" "$svg_file"
}
inject_svg_header agent/jankurai-badge.svg

test -s agent/jankurai-badge.svg
test -s agent/jankurai-badge.json

if [[ "${1:-}" == "--check" ]]; then
  git diff --exit-code -- README.md agent/jankurai-badge.svg agent/jankurai-badge.json
fi
