//! Profile-aware compile flow: emit TOML / YAML / passthrough.

use std::{fs, path::Path};

use anyhow::{Context, Result};

use crate::profile::{self, Profile};
use crate::runbook_lint;

mod discover;
mod emit;
mod report;
mod target;
mod validation;

#[cfg(test)]
mod tests;

pub use report::{CompileReport, InspectInfo, Outcome};

pub fn compile_one(source: &Path, out_override: Option<&Path>, check: bool) -> Result<Outcome> {
    let info = profile::detect(source)?;
    if let Profile::Runbook = &info.profile {
        validation::validate_runbook_profile(source, &info.raw)?;
        return Ok(Outcome::Unchanged(source.to_path_buf()));
    }
    if let Profile::Daemon { .. } = &info.profile {
        validation::validate_daemon_profile(source, &info.raw)?;
        return Ok(Outcome::Unchanged(source.to_path_buf()));
    }
    if let Profile::SuperWorkflow { .. } = &info.profile {
        // Validate before any emission so a bad manifest never produces output.
        validation::validate_superworkflow_profile(source, &info.raw)?;
    }
    let target = match out_override {
        Some(p) => p.to_path_buf(),
        None => target::default_target(source, &info.profile),
    };
    let (body, header) = emit::emit(&info.profile, &info.raw)?;
    let source_name = target::source_reference(source);
    let banner = format!(
        "{h}Generated by: zyalc — DO NOT EDIT BY HAND.\n{h}Source: {src}\n{h}Regenerate: `cargo run -p zyalc -- compile {src}`\n{h}zyalc: sha256={hash} source={src}\n",
        h = header,
        src = source_name,
        hash = target::sha256(&info.raw),
    );
    let final_bytes = match info.profile {
        Profile::Runbook => body, // runbook passthrough — sentinels are strict
        // SuperWorkflow emits canonical JSON; injecting a `# ...` banner would
        // make the file invalid JSON. Keep the body verbatim.
        Profile::SuperWorkflow { .. } => body,
        _ => format!("{banner}{body}"),
    };
    if check {
        // Explicit typed branching: a missing or unreadable target file is a
        // deliberate typed state (no prior compile output) distinct from an
        // empty file; both correctly produce an empty `existing` for the
        // equality check below.
        #[allow(clippy::manual_unwrap_or_default)]
        let existing: String = match fs::read_to_string(&target) {
            Ok(s) => s,
            Err(_) => String::new(),
        };
        if existing == final_bytes {
            return Ok(Outcome::Unchanged(target));
        }
        return Ok(Outcome::Drift(target));
    }
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;
    }
    // Explicit typed branching: see equivalent comment in the `check` arm
    // above — a missing target is a typed "no prior output" state.
    #[allow(clippy::manual_unwrap_or_default)]
    let existing: String = match fs::read_to_string(&target) {
        Ok(s) => s,
        Err(_) => String::new(),
    };
    if existing == final_bytes {
        return Ok(Outcome::Unchanged(target));
    }
    fs::write(&target, &final_bytes).with_context(|| format!("write {}", target.display()))?;
    Ok(Outcome::Wrote(target))
}

pub fn compile_all(root: &Path, check: bool) -> Result<CompileReport> {
    if check {
        runbook_lint::lint_all(root, true)?.error_if_findings()?;
    }
    let mut compiled = Vec::new();
    let mut unchanged = Vec::new();
    let mut drifted = Vec::new();
    for source in discover::discover(root)? {
        match compile_one(&source, None, check)? {
            Outcome::Wrote(p) => compiled.push(p),
            Outcome::Unchanged(p) => unchanged.push(p),
            Outcome::Drift(p) => drifted.push(p),
        }
    }
    Ok(CompileReport {
        compiled,
        unchanged,
        drifted,
    })
}

pub fn inspect(source: &Path) -> Result<InspectInfo> {
    let info = profile::detect(source)?;
    let target = match &info.profile {
        Profile::Runbook | Profile::Daemon { .. } => None,
        _ => Some(target::default_target(source, &info.profile)),
    };
    let schema = match &info.profile {
        Profile::DeclarativeToml { schema }
        | Profile::Workflow { schema }
        | Profile::Daemon { schema }
        | Profile::SuperWorkflow { schema } => Some(schema.clone()),
        Profile::Runbook => None,
    };
    Ok(InspectInfo {
        profile: info.profile.to_string(),
        target,
        schema,
    })
}
