//! `zyalc schema` (M17-cont) — generate the FlowGraph IR contract artifacts from
//! one definition: a draft-07 `flowgraph.schema.json` (constraining the emitted
//! IR, with `node_type` bound to the registered kinds) and a `zyal.d.ts`
//! TypeScript declaration. Deterministic; the generated schema validates the
//! flagship example IR (asserted in tests via the bundled mini-validator).

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde_json::{json, Value};

/// The draft-07 JSON Schema for the FlowGraph IR. `node_type` is constrained to
/// the registered kinds so an unknown kind fails schema validation too.
pub fn flowgraph_schema() -> Value {
    let kinds: Vec<Value> = crate::compile::registered_node_kinds()
        .into_iter()
        .map(Value::String)
        .collect();
    json!({
        "$comment": "Generated by `zyalc schema` from contracts/node-types.json — DO NOT EDIT BY HAND.",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://jekko.dev/schemas/flowgraph.schema.json",
        "title": "ZYAL FlowGraph IR",
        "type": "object",
        "required": ["schema", "id", "job", "nodes", "edges", "ir_version", "compile"],
        "properties": {
            "schema": { "const": "zyal/flowgraph@1" },
            "id": { "type": "string" },
            "ir_version": { "type": "string" },
            "zyal_version": { "type": "string" },
            "job": {
                "type": "object",
                "required": ["name", "objective"],
                "properties": { "name": { "type": "string" }, "objective": { "type": "string" } }
            },
            "nodes": { "type": "array", "items": { "$ref": "#/$defs/node" } },
            "edges": { "type": "array", "items": { "$ref": "#/$defs/edge" } },
            "compile": {
                "type": "object",
                "required": ["compiler", "source_hash", "registry_hash"],
                "properties": {
                    "compiler": { "type": "string" },
                    "source_hash": { "type": "string" },
                    "registry_hash": { "type": "string" }
                }
            }
        },
        "$defs": {
            "node": {
                "type": "object",
                "required": ["id", "node_type", "label"],
                "properties": {
                    "id": { "type": "string" },
                    "node_type": { "enum": kinds },
                    "label": { "type": "string" }
                }
            },
            "edge": {
                "type": "object",
                "required": ["id", "src", "dst", "kind"],
                "properties": {
                    "id": { "type": "string" },
                    "src": { "type": "string" },
                    "dst": { "type": "string" },
                    "kind": { "type": "string" }
                }
            }
        }
    })
}

/// A `zyal.d.ts` TypeScript declaration of the IR (one definition; the web reads
/// the byte-identical `node-types.json`, this types the emitted IR document).
pub fn zyal_dts() -> String {
    "// Generated by `zyalc schema` — DO NOT EDIT BY HAND.\n\
     export interface FlowGraphIr {\n\
     \x20 schema: \"zyal/flowgraph@1\";\n\
     \x20 id: string;\n\
     \x20 ir_version: string;\n\
     \x20 zyal_version?: string;\n\
     \x20 job: { name: string; objective: string };\n\
     \x20 nodes: FlowGraphNode[];\n\
     \x20 edges: FlowGraphEdge[];\n\
     \x20 compile: { compiler: string; source_hash: string; registry_hash: string };\n\
     }\n\
     export interface FlowGraphNode {\n\
     \x20 id: string;\n\
     \x20 node_type: string;\n\
     \x20 label: string;\n\
     \x20 [k: string]: unknown;\n\
     }\n\
     export interface FlowGraphEdge {\n\
     \x20 id: string;\n\
     \x20 src: string;\n\
     \x20 dst: string;\n\
     \x20 kind: string;\n\
     \x20 [k: string]: unknown;\n\
     }\n"
    .to_string()
}

/// Write the generated artifacts into `out_dir`. Returns the written paths.
pub fn write_schema(out_dir: &Path) -> Result<Vec<std::path::PathBuf>> {
    fs::create_dir_all(out_dir).with_context(|| format!("mkdir {}", out_dir.display()))?;
    let schema_path = out_dir.join("flowgraph.schema.json");
    let dts_path = out_dir.join("zyal.d.ts");
    let schema = format!("{}\n", serde_json::to_string_pretty(&flowgraph_schema())?);
    fs::write(&schema_path, schema).with_context(|| format!("write {}", schema_path.display()))?;
    fs::write(&dts_path, zyal_dts()).with_context(|| format!("write {}", dts_path.display()))?;
    Ok(vec![schema_path, dts_path])
}

// ---- a focused draft-07 validator (the subset this schema uses) -------------

/// Validate `instance` against `schema`, collecting human-readable errors. Covers
/// the subset of draft-07 the generated schema uses: type, required, properties,
/// items, enum, const, and `$ref` into `#/$defs/...`. Enough to genuinely assert
/// the emitted IR conforms — without an external JSON-Schema engine.
pub fn validate(schema: &Value, instance: &Value) -> Vec<String> {
    let mut errors = Vec::new();
    validate_at(schema, schema, instance, "$", &mut errors);
    errors
}

fn validate_at(root: &Value, schema: &Value, inst: &Value, path: &str, errors: &mut Vec<String>) {
    // $ref resolution (only #/$defs/<name>).
    if let Some(reff) = schema.get("$ref").and_then(Value::as_str) {
        if let Some(name) = reff.strip_prefix("#/$defs/") {
            if let Some(target) = root.get("$defs").and_then(|d| d.get(name)) {
                validate_at(root, target, inst, path, errors);
            } else {
                errors.push(format!("{path}: unresolved $ref {reff}"));
            }
        }
        return;
    }
    if let Some(expected) = schema.get("const") {
        if inst != expected {
            errors.push(format!("{path}: expected const {expected}, got {inst}"));
        }
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        if !values.contains(inst) {
            errors.push(format!("{path}: {inst} not in enum"));
        }
    }
    if let Some(ty) = schema.get("type").and_then(Value::as_str) {
        let ok = match ty {
            "object" => inst.is_object(),
            "array" => inst.is_array(),
            "string" => inst.is_string(),
            "number" => inst.is_number(),
            "boolean" => inst.is_boolean(),
            _ => true,
        };
        if !ok {
            errors.push(format!("{path}: expected type {ty}, got {inst}"));
            return; // a type mismatch makes deeper checks meaningless
        }
    }
    if let Some(req) = schema.get("required").and_then(Value::as_array) {
        for key in req.iter().filter_map(Value::as_str) {
            if inst.get(key).is_none() {
                errors.push(format!("{path}: missing required `{key}`"));
            }
        }
    }
    if let Some(props) = schema.get("properties").and_then(Value::as_object) {
        if let Some(obj) = inst.as_object() {
            for (key, subschema) in props {
                if let Some(child) = obj.get(key) {
                    validate_at(root, subschema, child, &format!("{path}.{key}"), errors);
                }
            }
        }
    }
    if let Some(items) = schema.get("items") {
        if let Some(arr) = inst.as_array() {
            for (i, item) in arr.iter().enumerate() {
                validate_at(root, items, item, &format!("{path}[{i}]"), errors);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn flagship_ir() -> Value {
        let path = format!("{}/tests/golden/35.ir.json", env!("CARGO_MANIFEST_DIR"));
        let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
        serde_json::from_str(&raw).expect("flagship golden is valid JSON")
    }

    #[test]
    fn generated_schema_validates_the_flagship_ir() {
        let errors = validate(&flowgraph_schema(), &flagship_ir());
        assert!(
            errors.is_empty(),
            "flagship IR must satisfy the generated schema: {errors:?}"
        );
    }

    #[test]
    fn schema_rejects_an_unknown_node_kind_and_missing_fields() {
        let schema = flowgraph_schema();
        // unknown node_type (not a registered kind)
        let bad_kind = json!({
            "schema": "zyal/flowgraph@1", "id": "x", "ir_version": "flowgraph.v3",
            "job": { "name": "n", "objective": "o" },
            "compile": { "compiler": "zyalc", "source_hash": "h", "registry_hash": "h" },
            "nodes": [{ "id": "a", "node_type": "not_a_real_kind", "label": "A" }],
            "edges": []
        });
        assert!(
            !validate(&schema, &bad_kind).is_empty(),
            "unknown node_type must fail"
        );
        // missing top-level required field (job)
        let missing = json!({ "schema": "zyal/flowgraph@1", "id": "x", "ir_version": "v", "nodes": [], "edges": [], "compile": {"compiler":"z","source_hash":"h","registry_hash":"h"} });
        assert!(validate(&schema, &missing)
            .iter()
            .any(|e| e.contains("job")));
    }

    #[test]
    fn schema_and_dts_are_deterministic() {
        assert_eq!(flowgraph_schema(), flowgraph_schema());
        assert_eq!(zyal_dts(), zyal_dts());
        assert!(zyal_dts().contains("FlowGraphIr") && zyal_dts().contains("node_type"));
    }
}
